import { WeatherCodeInfo } from '../types/weather';

export const WMO_WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Cloudless, clear skies with maximum sunshine visibility',
    iconName: 'Sun',
    category: 'clear',
    severity: 'calm',
    bgGradient: {
      day: 'from-sky-500/20 via-blue-600/10 to-amber-500/10',
      night: 'from-indigo-950/50 via-slate-900/60 to-purple-950/40',
    },
    cardAccent: 'border-sky-500/30 text-sky-400',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with scattered high-altitude wispy clouds',
    iconName: 'SunMedium',
    category: 'clear',
    severity: 'calm',
    bgGradient: {
      day: 'from-sky-500/20 via-blue-500/10 to-indigo-500/10',
      night: 'from-slate-900/60 via-indigo-950/40 to-slate-950/60',
    },
    cardAccent: 'border-sky-500/30 text-sky-400',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'A pleasant blend of sunshine and passing cumulus clouds',
    iconName: 'CloudSun',
    category: 'cloudy',
    severity: 'calm',
    bgGradient: {
      day: 'from-sky-600/20 via-blue-700/10 to-slate-800/20',
      night: 'from-slate-900/70 via-slate-800/40 to-indigo-950/40',
    },
    cardAccent: 'border-blue-400/30 text-blue-300',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Thick continuous cloud cover blocking direct sunlight',
    iconName: 'Cloud',
    category: 'cloudy',
    severity: 'calm',
    bgGradient: {
      day: 'from-slate-700/30 via-slate-800/20 to-slate-900/40',
      night: 'from-slate-900/80 via-slate-950/70 to-zinc-950/80',
    },
    cardAccent: 'border-slate-500/30 text-slate-300',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Dense ground-level fog reducing horizontal visibility',
    iconName: 'CloudFog',
    category: 'fog',
    severity: 'moderate',
    bgGradient: {
      day: 'from-zinc-700/30 via-slate-700/20 to-slate-900/50',
      night: 'from-slate-900/80 via-zinc-900/60 to-slate-950/80',
    },
    cardAccent: 'border-zinc-500/30 text-zinc-300',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming frost crystals on cold surfaces',
    iconName: 'CloudFog',
    category: 'fog',
    severity: 'moderate',
    bgGradient: {
      day: 'from-cyan-800/25 via-slate-800/30 to-blue-950/50',
      night: 'from-slate-950/80 via-cyan-950/40 to-slate-900/80',
    },
    cardAccent: 'border-cyan-400/30 text-cyan-300',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Fine, gentle water droplets falling consistently',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    severity: 'calm',
    bgGradient: {
      day: 'from-teal-700/20 via-sky-800/20 to-slate-900/40',
      night: 'from-slate-900/70 via-teal-950/40 to-slate-950/70',
    },
    cardAccent: 'border-teal-400/30 text-teal-300',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady mist and drizzle dampening roads and outerwear',
    iconName: 'CloudDrizzle',
    category: 'drizzle',
    severity: 'moderate',
    bgGradient: {
      day: 'from-cyan-700/25 via-slate-800/30 to-slate-900/50',
      night: 'from-slate-950/80 via-cyan-950/50 to-slate-900/70',
    },
    cardAccent: 'border-teal-400/30 text-teal-300',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle creating puddles and slick pavements',
    iconName: 'CloudRain',
    category: 'drizzle',
    severity: 'moderate',
    bgGradient: {
      day: 'from-blue-700/30 via-slate-800/30 to-slate-900/50',
      night: 'from-slate-950/80 via-blue-950/50 to-slate-900/70',
    },
    cardAccent: 'border-blue-400/30 text-blue-300',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Icy drizzle forming a slippery glaze on cold surfaces',
    iconName: 'CloudHail',
    category: 'drizzle',
    severity: 'warning',
    bgGradient: {
      day: 'from-cyan-600/30 via-slate-800/40 to-slate-900/60',
      night: 'from-cyan-950/60 via-slate-950/80 to-blue-950/60',
    },
    cardAccent: 'border-cyan-400/40 text-cyan-300',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Hazardous icy drizzle causing black ice conditions',
    iconName: 'CloudHail',
    category: 'drizzle',
    severity: 'warning',
    bgGradient: {
      day: 'from-cyan-700/35 via-blue-900/40 to-slate-950/70',
      night: 'from-cyan-950/70 via-slate-950/90 to-blue-950/70',
    },
    cardAccent: 'border-cyan-300/40 text-cyan-200',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Occasional light rain showers; umbrella recommended',
    iconName: 'CloudRain',
    category: 'rain',
    severity: 'moderate',
    bgGradient: {
      day: 'from-sky-700/30 via-blue-800/20 to-slate-900/50',
      night: 'from-slate-900/80 via-blue-950/50 to-slate-950/80',
    },
    cardAccent: 'border-sky-400/30 text-sky-300',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Continuous steady rainfall; wet roads and walkways',
    iconName: 'CloudRain',
    category: 'rain',
    severity: 'moderate',
    bgGradient: {
      day: 'from-blue-700/35 via-indigo-900/30 to-slate-950/60',
      night: 'from-slate-950/80 via-blue-950/60 to-slate-900/80',
    },
    cardAccent: 'border-blue-400/40 text-blue-300',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Torrential downpour with high runoff and localized pooling',
    iconName: 'CloudRainWind',
    category: 'rain',
    severity: 'warning',
    bgGradient: {
      day: 'from-blue-800/40 via-indigo-950/50 to-slate-950/70',
      night: 'from-blue-950/90 via-slate-950/90 to-indigo-950/80',
    },
    cardAccent: 'border-blue-500/40 text-blue-300',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Sub-freezing rain creating slick conditions on travel routes',
    iconName: 'CloudHail',
    category: 'rain',
    severity: 'warning',
    bgGradient: {
      day: 'from-cyan-800/40 via-slate-900/50 to-slate-950/80',
      night: 'from-cyan-950/80 via-slate-950/90 to-indigo-950/70',
    },
    cardAccent: 'border-cyan-400/40 text-cyan-300',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain causing significant ice accretion',
    iconName: 'CloudHail',
    category: 'rain',
    severity: 'severe',
    bgGradient: {
      day: 'from-cyan-900/50 via-slate-950/70 to-blue-950/80',
      night: 'from-cyan-950/90 via-slate-950/95 to-slate-950/90',
    },
    cardAccent: 'border-cyan-300/50 text-cyan-200',
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Gentle snowflakes falling with minor accumulation',
    iconName: 'CloudSnow',
    category: 'snow',
    severity: 'moderate',
    bgGradient: {
      day: 'from-indigo-700/25 via-blue-800/20 to-slate-900/50',
      night: 'from-slate-900/80 via-indigo-950/60 to-slate-950/80',
    },
    cardAccent: 'border-indigo-300/30 text-indigo-200',
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Steadily accumulating snow blanketing surfaces',
    iconName: 'CloudSnow',
    category: 'snow',
    severity: 'warning',
    bgGradient: {
      day: 'from-indigo-600/30 via-slate-800/40 to-slate-950/60',
      night: 'from-indigo-950/80 via-slate-950/90 to-slate-900/80',
    },
    cardAccent: 'border-indigo-300/40 text-indigo-200',
  },
  75: {
    code: 75,
    label: 'Heavy Snowfall',
    description: 'Intense snowfall causing snow accumulation and reduced visibility',
    iconName: 'Snowflake',
    category: 'snow',
    severity: 'warning',
    bgGradient: {
      day: 'from-indigo-700/40 via-blue-950/60 to-slate-950/80',
      night: 'from-slate-950/90 via-indigo-950/80 to-blue-950/80',
    },
    cardAccent: 'border-indigo-200/50 text-indigo-100',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Tiny, opaque ice grains falling from layered clouds',
    iconName: 'Snowflake',
    category: 'snow',
    severity: 'moderate',
    bgGradient: {
      day: 'from-slate-700/30 via-indigo-900/30 to-slate-950/60',
      night: 'from-slate-950/80 via-indigo-950/70 to-slate-900/80',
    },
    cardAccent: 'border-indigo-300/30 text-indigo-200',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Brief, passing rain showers with sunny intervals',
    iconName: 'CloudSunRain',
    category: 'rain',
    severity: 'calm',
    bgGradient: {
      day: 'from-sky-600/25 via-blue-700/20 to-slate-900/50',
      night: 'from-slate-900/80 via-sky-950/40 to-slate-950/80',
    },
    cardAccent: 'border-sky-400/30 text-sky-300',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Frequent passing rain squalls; carry wet weather gear',
    iconName: 'CloudRain',
    category: 'rain',
    severity: 'moderate',
    bgGradient: {
      day: 'from-blue-700/30 via-sky-900/30 to-slate-950/60',
      night: 'from-slate-950/80 via-blue-950/60 to-slate-900/80',
    },
    cardAccent: 'border-blue-400/40 text-blue-300',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Sudden high-intensity squalls with rapid puddle formation',
    iconName: 'CloudRainWind',
    category: 'rain',
    severity: 'warning',
    bgGradient: {
      day: 'from-blue-900/45 via-indigo-950/60 to-slate-950/80',
      night: 'from-blue-950/90 via-slate-950/95 to-indigo-950/90',
    },
    cardAccent: 'border-blue-400/50 text-blue-200',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Scattered short-lived snowfall bursts',
    iconName: 'CloudSnow',
    category: 'snow',
    severity: 'moderate',
    bgGradient: {
      day: 'from-indigo-600/25 via-blue-800/30 to-slate-900/60',
      night: 'from-slate-950/80 via-indigo-950/60 to-slate-900/80',
    },
    cardAccent: 'border-indigo-300/30 text-indigo-200',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls with sudden drops in visibility',
    iconName: 'Snowflake',
    category: 'snow',
    severity: 'warning',
    bgGradient: {
      day: 'from-indigo-700/40 via-blue-950/60 to-slate-950/80',
      night: 'from-slate-950/90 via-indigo-950/80 to-blue-950/80',
    },
    cardAccent: 'border-indigo-300/50 text-indigo-100',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Active storm cells with thunder claps and lightning flashes',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    severity: 'warning',
    bgGradient: {
      day: 'from-purple-800/40 via-amber-900/20 to-slate-950/80',
      night: 'from-purple-950/80 via-slate-950/90 to-amber-950/40',
    },
    cardAccent: 'border-amber-400/50 text-amber-300',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Slight Hail',
    description: 'Thunderstorm accompanied by small ice pellets and hail',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    severity: 'severe',
    bgGradient: {
      day: 'from-purple-900/50 via-cyan-900/30 to-slate-950/85',
      night: 'from-purple-950/90 via-cyan-950/50 to-slate-950/95',
    },
    cardAccent: 'border-amber-400/60 text-amber-300',
  },
  99: {
    code: 99,
    label: 'Thunderstorm with Heavy Hail',
    description: 'Dangerous severe storm with large destructive hail and high winds',
    iconName: 'CloudLightning',
    category: 'thunderstorm',
    severity: 'severe',
    bgGradient: {
      day: 'from-red-900/40 via-purple-950/60 to-slate-950/90',
      night: 'from-red-950/80 via-purple-950/90 to-slate-950/95',
    },
    cardAccent: 'border-rose-400/60 text-rose-300',
  },
};

export function getWeatherCodeInfo(code: number): WeatherCodeInfo {
  return (
    WMO_WEATHER_CODES[code] || {
      code,
      label: 'Variable Conditions',
      description: 'Typical atmospheric weather conditions',
      iconName: 'CloudSun',
      category: 'cloudy',
      severity: 'calm',
      bgGradient: {
        day: 'from-sky-700/20 via-slate-800/30 to-slate-900/50',
        night: 'from-slate-900/80 via-slate-950/80 to-slate-900/80',
      },
      cardAccent: 'border-slate-500/30 text-slate-300',
    }
  );
}
